export const ROUTES = {
  ACCORDION: "/accordion/",
  AUTOCOMPLETE: "/autocomplete/",
  AVATAR: "/avatar/",
  BUTTON: "/button/",
  CHECKBOX: "/checkbox/",
  DOCUMENT_VIEWER: "/document-viewer/",
  FORM_FIELD: "/form-field/",
  HOME: "/",
  HAMBURGER: "/hamburger/",
  ICON: "/icon/",
  ICON_BUTTON: "/icon-button/",
  MODAL: "/modal/",
  OVERLAY: "/overlay/",
  RIPPLE: "/ripple/",
  SCROLLBAR: "/scrollbar/",
  SELECT: "/select/",
  SIDEBAR: "/sidebar/",
};

